#!/bin/bash 
if [ "$(id -u)" != "0" ]; then 
    echo "This script must be run as #root" 1>&2 
    exit 1 
fi

case $1 in
    remove) 
        sudo rm -f /usr/share/onboard/layouts/Compact-ko.onboard
        sudo rm -f /usr/share/onboard/layouts/Full-Keyboard-ko.onboard
        gsettings set org.onboard layout '/usr/share/onboard/layouts/Compact.onboard'
        gsettings set org.onboard system-theme-tracking-enabled false
        ;;
    help|-h|--h) 
        echo "Usage"
        echo "----"
        echo "INSTALL) sudo $0 install"
        echo "REMOVE) sudo $0 remove"
        exit 0
        ;;
    *) 
        sudo install -D -m 644 debian/usr/share/onboard/layouts/Compact-ko.onboard /usr/share/onboard/layouts/Compact-ko.onboard
        sudo install -D -m 644 debian/usr/share/onboard/layouts/Full-Keyboard-ko.onboard /usr/share/onboard/layouts/Full-Keyboard-ko.onboard

        #  check gsetting values gsettings list-keys org.onboard.gschema
        # gsettings list-keys org.onboard theme

        # Select Compact-ko.onboard or Full-Keyboard-ko.onboard
        gsettings set org.onboard layout '/usr/share/onboard/layouts/Full-Keyboard-ko.onboard'

        # If you want to change font, edit to below You must be install nanum
        # font first ex) sudo apt install fonts-nanum
        #
        # gsettings set org.onboard key-label-font
        # '/usr/share/fonts/truetype/nanum/NanumGothic.ttf'

        # 시스템 테마를 따르도록 설정
        gsettings set org.onboard system-theme-tracking-enabled true
        ;;
esac
