#!/bin/bash

### Getting OS Information
if [ -f /etc/lsb-release ]; then
    . /etc/lsb-release
    DIST=$DISTRIB_ID
    DIST_VER=$DISTRIB_RELEASE
else
    DIST="Unknown"
    DIST_VER="Unknown"
fi

if [ "$XDG_CURRENT_DESKTOP" = "" ]
then
  desktop=$(echo "$XDG_DATA_DIRS" | sed 's/.*\(xfce\|kde\|gnome\).*/\1/')
else
  desktop=$XDG_CURRENT_DESKTOP
fi
# convert to lower case
desktop=${desktop,,} 

case $DIST in
    HamoniKR|Ubuntu|LinuxMint)
        # Get the Real Username
        RUID=$(who | awk 'FNR == 1 {print $1}')
        # Translate Real Username to Real User ID
        RUSER_UID=$(id -u ${RUID})
        sudo -u ${RUID} DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${RUSER_UID}/bus" gsettings set org.onboard layout '/usr/share/onboard/layouts/Full-Keyboard-ko.onboard'
        sudo -u ${RUID} DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${RUSER_UID}/bus" gsettings set org.onboard system-theme-tracking-enabled true
        
        # DE 종류에 따라서 기본 greeter 설정가능 여부가 다름
        case $desktop in
            deepin)
                sudo mv /usr/share/onboard/layouts/Small.onboard /usr/share/onboard/layouts/Small.onboard.bak
                sudo ln -sf /usr/share/onboard/layouts/Compact-ko.onboard /usr/share/onboard/layouts/Small.onboard
            ;;
            x-cinnamon)
                sudo mv /usr/share/onboard/layouts/Compact.onboard /usr/share/onboard/layouts/Compact.onboard.bak
                sudo ln -sf /usr/share/onboard/layouts/Compact-ko.onboard /usr/share/onboard/layouts/Compact.onboard
            ;;
            *)
            ;;    
        esac        
    ;;
    *)
    ;;    
esac


