#!/bin/bash

### Getting OS Information
if [ -f /etc/lsb-release ]; then
    . /etc/lsb-release
    DIST=$DISTRIB_ID
    DIST_VER=$DISTRIB_RELEASE
else
    DIST="Unknown"
    DIST_VER="Unknown"
fi

if [ "$XDG_CURRENT_DESKTOP" = "" ]
then
  desktop=$(echo "$XDG_DATA_DIRS" | sed 's/.*\(xfce\|kde\|gnome\).*/\1/')
else
  desktop=$XDG_CURRENT_DESKTOP
fi
# convert to lower case
desktop=${desktop,,} 

RUID=$(who | awk 'FNR == 1 {print $1}')
if [ ! -z "$RUID" ] ; then

    case $DIST in
        HamoniKR|Ubuntu|LinuxMint)
        # Get the Real Username
        RUID=$(who | awk 'FNR == 1 {print $1}')
        # Translate Real Username to Real User ID
        RUSER_UID=$(id -u ${RUID})
        if [ ! -z "$RUID" ] ; then
            sudo -u ${RUID} DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${RUSER_UID}/bus" gsettings set org.onboard layout '/usr/share/onboard/layouts/Compact.onboard'
            sudo -u ${RUID} DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${RUSER_UID}/bus" gsettings set org.onboard system-theme-tracking-enabled false
        fi        
        ;;
        *)
        ;;    
    esac

    case $desktop in
        deepin)
            if [ -f "/usr/share/onboard/layouts/Small.onboard" ]; then
                rm -f /usr/share/onboard/layouts/Small.onboard
            fi
            if [ -f "/usr/share/onboard/layouts/Small.onboard.bak" ]; then
                mv /usr/share/onboard/layouts/Small.onboard.bak /usr/share/onboard/layouts/Small.onboard
            fi
        ;;
        x-cinnamon|gnome)
            if [ -f "/usr/share/onboard/layouts/Compact.onboard" ]; then
                rm -f /usr/share/onboard/layouts/Compact.onboard
            fi
            if [ -f "/usr/share/onboard/layouts/Compact.onboard.bak" ]; then
                mv /usr/share/onboard/layouts/Compact.onboard.bak /usr/share/onboard/layouts/Compact.onboard
            fi
        ;;    
        *)
        ;;    
    esac

fi
