#!/bin/bash

### Getting OS Information
if [ -f /etc/lsb-release ]; then
    . /etc/lsb-release
    DIST=$DISTRIB_ID
    DIST_VER=$DISTRIB_RELEASE
else
    DIST="Unknown"
    DIST_VER="Unknown"
fi

if [ "$XDG_CURRENT_DESKTOP" = "" ]
then
  desktop=$(echo "$XDG_DATA_DIRS" | sed 's/.*\(xfce\|kde\|gnome\).*/\1/')
else
  desktop=$XDG_CURRENT_DESKTOP
fi
# convert to lower case
desktop=${desktop,,} 

case $DIST in
    HamoniKR|Ubuntu|LinuxMint)
        gsettings set org.onboard layout '/usr/share/onboard/layouts/Compact.onboard'
        gsettings set org.onboard system-theme-tracking-enabled false
    ;;
    *)
    ;;    
esac

case $desktop in
    deepin)
        sudo rm -f /usr/share/onboard/layouts/Small.onboard
        sudo mv /usr/share/onboard/layouts/Small.onboard.bak /usr/share/onboard/layouts/Small.onboard
    ;;
    x-cinnamon)
        sudo rm -f /usr/share/onboard/layouts/Compact.onboard
        sudo mv /usr/share/onboard/layouts/Compact.onboard.bak /usr/share/onboard/layouts/Compact.onboard
    ;;    
    *)
    ;;    
esac
